---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prod
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: GitRepository
        name: devops-toolkit
  interval: 30s
  targetNamespace: production
  values:
          image:
               tag: 1.15.0
